site_name: YETL
site_url: https://yetl.io/
site_author: Shaun Ryan
site_description: >-
  Data engineering framework to template data flow pipelines
  and implement transforms in python
edit_uri: ""
# Repository
repo_name: sibytes/yetl
repo_url: https://github.com/sibytes/yetl

# Copyright
copyright: Copyright &copy; 2021 - 2023 Shaun Ryan

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  # logo: assets/logo.png

  name: material
  features:
   # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  # icon:
  logo: assets/logo.png
  


nav:
    - index.md
    - Project: project.md
    - On-Board Datafeed: on-board-datafeed.md
    - Reference:
      - Project Config: reference/project-config.md
      - Table Config: reference/table-config.md
      - Pipeline Config: reference/pipeline-config.md
      - Python API: reference/python-api.md
    - About: about.md

site_name: YETL

plugins:
  - exporter:
      logging:
        level: debug
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, true]
          concurrency: 16
          stylesheets:
            - resources/stylesheets/pdf.scss
          covers:
            front: resources/templates/covers/front.html.j2
            back: resources/templates/covers/back.html.j2
          browser:
            debug: false
          aggregator:
            enabled: !ENV [MKDOCS_EXPORTER_PDF_AGGREGATOR, true]
            output: documentation.pdf
            covers: limits
      buttons:
        - title: View as PDF
          icon: material-file-move-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes:
            target: _blank
            href: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.href
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes