site_url: https://sibytes.github.io/yetl/
site_author: Shaun Ryan
site_description: >-
  Data engineering framework to template data flow pipelines
  and implement transforms in python
# Repository
repo_name: sibytes/yetl
repo_url: https://github.com/sibytes/yetl

# Copyright
copyright: Copyright &copy; 2021 - 2023 Shaun Ryan

theme:
  # logo: assets/logo.png
  name: material
  features:
   # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  # icon:
  logo: assets/logo.png
  


nav:
    - YETL?: 
      - index.md
      - Development Workflow: yetl/development_workflow.md
    - Tutorial: tutorial.md
    - Examples: examples.md
    - Reference:
        - Cli: reference/cli.md
        - Projects: reference/projects.md
        - Environments: reference/environments.md
        - Schema Repo: reference/schema_repo.md
        - Auditing: reference/auditing.md
        - Sources:
          - reference/sources/index.md
          - Reader: reference/sources/source_reader.md
          - SQL Reader: reference/sources/source_sql_reader.md
        - Destinations:
          - reference/destinations/index.md
          - Delta Writer: reference/destinations/destination_delta_writer.md
    - About: about.md
site_name: YETL
